### ISSUE TITLE
Audio type not supported

### ISSUE THREAD

**Issue by ghost** [microsoft/DNS-Challenge#6]
Hi,
I cloned the repository (i opened 'git bash' application and used the command 'git clone https://github.com/microsoft/DNS-Challenge.git').
It took a few minutes but it downloaded all the files and datasets.
But the wav files seem to be corrupted. Can't play the files using window's media tools. It says that the file is not playable, and that something is corrupted.

I didn't manage to install and use the LFS option... 
So i just waited for everything to download (didn't take that much time).
Is it necessary to work with LFS in order to download the data correctly?

My current status:
When i ran the file "noisyspeech_synthesizer_multiprocessing.py" i got the following message:
"WARNING: Audio type not supported " and the program terminates.
I blame the corrupted wav files.

How can i download the wav files correctly?

BTW, the code requires the "pandas" package too.

**Comment by mpariente** [comment]
I can suggest you have a look at [this](https://github.com/mpariente/AsSteroid/tree/master/egs/dns_challenge). We created a basic recipe for the challenge in `asteroid`, it includes installing git-lfs without root, data download, dataset creation and basic scripts for training.

**Comment by hadaso** [comment]
Thanks for your useful answer, but i can't find the "download or clone" option for the "asteroid" code...
I will take the risk of sounding stupid but... how am i supposed to get the code?
Thanks.

![Capture](https://user-images.githubusercontent.com/55354058/75262511-500f3780-57f5-11ea-92ba-2ef97a045098.PNG)

**Comment by mpariente** [comment]
No problem, the recipe is in a sub-directory so you have to go to master and clone it [from here](https://github.com/mpariente/AsSteroid) instead.

**Comment by hadaso** [comment]
Hi again, i tried for the last several days to use your script in order to install and download the data. i used an external hard-disk in order to supply the 320GB storage that was requested. Changed the 'storage_data' as was instructed.
Still - the script fails after the first stage.... i don't know why (screenshot is attached).
I would appreciate any advice, or a better working script... :-(  
![Screenshot from 2020-03-04 18-10-09](https://user-images.githubusercontent.com/55354058/75899892-cab70300-5e44-11ea-9629-ac141255057e.png)

**Comment by mpariente** [comment]
Hi, I'm sorry about that, it's a small mistake that I just fixed, you can start again and it should work.
Please, if you encounter problems with the recipe from asteroid, open an issue there instead of here, thanks.
