### ISSUE TITLE
the wav files in the datasets may be damaged, and cannot open them by any media player

### ISSUE THREAD

**Issue by xiaoqi91** [microsoft/DNS-Challenge#95]
I downloaded the datasets to my own pc, and I can't open any of them. The error comes up in audition like this:
![图片](https://user-images.githubusercontent.com/43266993/146516483-78d14b4f-908e-4f82-a245-a95e70e96d41.png)
Could you please update the wav files in the datasets? Thank you so much!

**Comment by motus** [comment]
@xiaoqi91 Are you saying that **all** our clips are corrupted? I wonder why no one else is complaining about it. I would guess that there is some issue with your player or something.

Anyway, I've just listened to the clip from your screenshot and it sounds just fine.  (By the way, *don't* use screenshots - I would much prefer the text path that I can copy and paste instead of typing `__5V2Njkf5M.wav`).

Just in case, here's a file with SHA1 hashes of all DNS3 and DNS4 clips:
https://dns4public.blob.core.windows.net/dns4archive/dns4-datasets-files-sha1.csv.bz2
Please check if your copy is ok and reopen this issue if the file in the archive is corrupted.

**Comment by Abalam-29895** [comment]
I am also facing the same issue while downloading [download-dns-challenge-2.sh](https://github.com/microsoft/DNS-Challenge/blob/2db96d5f75257df764a6ef66513b4b97bc707f30/download-dns-challenge-2.sh). The files are getting corrupted after unzipping (manually and using shell script). Can you provide a solution? Thank you!
